version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mediedu-data:/data/db
  backend:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/mediedu
    ports:
      - 4000:4000
    depends_on:
      - mongo
volumes:
  mediedu-data:
